language: cpp
script: "cd hts_engine_API && chmod +x configure && ./configure && make && cd .. && chmod +x configure && ./configure --with-hts-engine-header-path=$(pwd)/hts_engine_API/include --with-hts-engine-library-path=$(pwd)/hts_engine_API/lib && make"
addons:
  apt:
    packages:
      - git clone http://git.sv.gnu.org/r/autoconf.git
      - cd autoconf
      - aclocal -I m4
      - automake -a
      - autoconf
      - ./configure --prefix=/usr
      - make
      - sudo make install